title: Curtis Pearson
<<<<<<< HEAD
description: Portfolio website for Curtis Pearson software engineer
=======
description: Portfolio website for Curtis Pearson software engineer
>>>>>>> f4aa27137aada43dc53c23f5da976af540e0e962
